// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpH7efef-gdTf814lQZ3d3QEXHqWDfwM',
    appId: '1:755731644505:web:18fbf8a261d82eda3cb148',
    messagingSenderId: '755731644505',
    projectId: 'vetdigital-1e52c',
    authDomain: 'vetdigital-1e52c.firebaseapp.com',
    storageBucket: 'vetdigital-1e52c.appspot.com',
    measurementId: 'G-0QZWVEPRKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOyENgdnyOM3qozDBSGU_5C0TEYSwH268',
    appId: '1:755731644505:android:5e06fc4a65eead453cb148',
    messagingSenderId: '755731644505',
    projectId: 'vetdigital-1e52c',
    storageBucket: 'vetdigital-1e52c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArkU-GyD1DPOklH-rm-Sy4MLJNGBI2mlg',
    appId: '1:755731644505:ios:410b387b8a10e5203cb148',
    messagingSenderId: '755731644505',
    projectId: 'vetdigital-1e52c',
    storageBucket: 'vetdigital-1e52c.appspot.com',
    iosClientId: '755731644505-md9c0ftnqt98djclj4l70qf3st1ucpgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArkU-GyD1DPOklH-rm-Sy4MLJNGBI2mlg',
    appId: '1:755731644505:ios:410b387b8a10e5203cb148',
    messagingSenderId: '755731644505',
    projectId: 'vetdigital-1e52c',
    storageBucket: 'vetdigital-1e52c.appspot.com',
    iosClientId: '755731644505-md9c0ftnqt98djclj4l70qf3st1ucpgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetDigital',
  );
}
